name: ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0
  carousel_slider: ^4.2.1
  motion_blur: ^0.0.2
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  shaders:
        - packages/motion_blur/shaders/motion_blur.glsl

  assets:
    - assets/images/